print('my name is ALEX')
print("I was born in May")
print("My name is Lucas")
print("I was born in June")
print("My favorite food is hamburgers")
print("I was born in Michigan")
print("I am CANCER")
print("I enjoy shit ass rap")